### ISSUE TITLE
Unable to connect network table for debugging.

### ISSUE THREAD

**Issue by Rmccawley** [nleach999/Vortx3735.Shuffleboard.2019.WidgetTutorial#1]
In watching your Eclipse based tutorials you show how to enable the network table server to allow for the adding of network table data for debugging. Is there anyway to do this for VS Code? When running the debugger it successfully launches Shuffleboard but I get an network table connection error (NT: connect() to localhost port 1735 timed out). I have not found a way of enabling a server in VS Code like the one you use for Eclipse.

**Comment by nleach999** [comment]
In VSCode, use CTRL-SHIFT-P and type "WPILib: Start Tool" then it will give you a list of tools.  Choose "Outline Viewer".  When the Outline Viewer starts, turn on the "Server Mode" button then click start.  If your Shuffleboard is set to connect to "localhost" (File->Preferences->Plugins->NetworkTables->Server). Outline Viewer will show you how many clients are connected at the bottom of the window. 

In outline viewer you can add values with path separators to get them into heirarchies.  Try the differences between "/foo" and "/bar/foo" or even "/a/b/c/d/e/foo".  You'll see your data items and groups show up in the Sources of Shuffleboard.
